<#!
Build a standalone SQLCMD-mode script from the canonical schema and migrations.
This only writes a SQL file; it does not connect to or modify SQL Server.
!#>
[CmdletBinding()]
param(
    [ValidatePattern('^[A-Za-z][A-Za-z0-9_]{0,127}$')]
    [string]$DatabaseName = 'HelmetCartelDB'
)
$ErrorActionPreference = 'Stop'
$databaseRoot = Split-Path $PSScriptRoot -Parent
$outputPath = Join-Path $PSScriptRoot 'new_database_minimal.sql'
$files = @(
    'schema/01_schema.sql',
    'schema/03_product_gallery.sql',
    'schema/04_product_specifications.sql',
    'schema/05_product_order_count_index.sql',
    'schema/06_admin_portal_migration.sql',
    'queries/03_procedures_and_queries.sql',
    'queries/04_product_specification_procedures.sql',
    'queries/05_admin_operations.sql',
    'queries/06_admin_catalog.sql',
    'schema/08_discounts_and_search_migration.sql',
    'schema/09_inventory_audit_and_global_search.sql',
    'schema/10_product_edit_and_gallery.sql',
    'schema/11_delete_product_and_permissions.sql',
    'schema/12_update_search_and_variants.sql',
    'schema/13_dynamic_admin_metrics.sql',
    'schema/14_pos_and_inventory_drilldown.sql',
    'schema/15_catalog_enhancements.sql',
    'schema/16_pos_global_search.sql',
    'schema/17_active_catalog_visibility.sql',
    'schema/18_delivery_fulfillment_migration.sql',
    'setup/minimal_seed.sql',
    'setup/dashboard_sample_data.sql'
)
$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine(@"
-- GENERATED by Build-MinimalDatabase.ps1. Edit source scripts and rebuild.
-- Run this complete file in a normal SSMS query window.
-- Stops if the database already exists. Never drops or overwrites a database.
USE [master];
GO
IF DB_ID(N'$DatabaseName') IS NOT NULL
    THROW 52091, 'Target database already exists. Choose a new database name.', 1;
GO
CREATE DATABASE [$DatabaseName];
GO
USE [$DatabaseName];
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
"@)
foreach ($relativePath in $files) {
    $source = [IO.File]::ReadAllText((Join-Path $databaseRoot $relativePath))
    if ($relativePath -eq 'schema/01_schema.sql') {
        $start = $source.IndexOf('SET ANSI_NULLS ON;')
        if ($start -lt 0) { throw 'Base schema preamble was not recognized.' }
        $source = $source.Substring($start)
    }
    # Remove fixed database context from every included source. All batches
    # must stay in the new database, including migrations with bracketed USE.
    $source = [regex]::Replace($source, '(?im)^\s*USE\s+\[?HelmetCartel(?:Minimal)?DB\]?\s*;\s*$', '')
    [void]$builder.AppendLine("-- Source: $relativePath")
    [void]$builder.AppendLine($source)
    [void]$builder.AppendLine("`nGO")
}
[IO.File]::WriteAllText($outputPath, $builder.ToString(), (New-Object System.Text.UTF8Encoding($true)))
Write-Output "Created $outputPath for $DatabaseName (5 products, 10 SKUs, 6 sample orders)."
