# Preserve the latest active-only search contract while eliminating FullName storage.
$ErrorActionPreference = 'Stop'
$databaseRoot = Split-Path $PSScriptRoot -Parent
$source = [IO.File]::ReadAllText((Join-Path $databaseRoot 'schema/17_active_catalog_visibility.sql'))
$definition = [regex]::Match($source, '(?ims)^CREATE OR ALTER PROCEDURE dbo\.sp_AdminGlobalSearch\b.*?(?=^GO\s*$)').Value
if (-not $definition -or $definition -match '\bu\.FullName\b') { throw 'Search must derive user display names.' }
$sql = @'
-- Generated by Build-NormalizationMigration.ps1.
-- Run after migration 23. The upgrade runner supplies backup and transaction handling.
-- FullName remains an API result alias, never a Users table column.
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
'@ + "`r`n" + $definition + "`r`nGO`r`n" + @'
IF COL_LENGTH(N'dbo.Users', N'FullName') IS NOT NULL
BEGIN
    IF EXISTS (
        SELECT 1 FROM sys.sql_expression_dependencies
        WHERE referenced_id = OBJECT_ID(N'dbo.Users')
          AND referenced_minor_id = COLUMNPROPERTY(OBJECT_ID(N'dbo.Users'), N'FullName', 'ColumnId')
          AND referencing_id <> OBJECT_ID(N'dbo.Users')
    )
        THROW 53034, N'FullName still has database dependencies; review before dropping it.', 1;
    ALTER TABLE dbo.Users DROP COLUMN FullName;
END;
GO
'@
[IO.File]::WriteAllText((Join-Path $databaseRoot 'schema/24_remove_redundant_user_fullname.sql'), $sql, (New-Object System.Text.UTF8Encoding($true)))
