# Rebuild the read-only visibility migration from the latest canonical procedures.
$ErrorActionPreference = 'Stop'
$databaseRoot = Split-Path $PSScriptRoot -Parent
$sources = @('queries/03_procedures_and_queries.sql', 'queries/04_product_specification_procedures.sql',
    'queries/05_admin_operations.sql', 'queries/06_admin_catalog.sql') +
    @(Get-ChildItem (Join-Path $databaseRoot 'schema') -Filter '*.sql' |
      Where-Object { $_.Name -match '^(08|09|10|11|12|13|14|15|16)_' } |
      Sort-Object Name | ForEach-Object { 'schema/' + $_.Name })
$procedures = @{}
foreach ($source in $sources) {
    $sql = [IO.File]::ReadAllText((Join-Path $databaseRoot $source))
    foreach ($batch in [regex]::Split($sql, '(?im)^\s*GO\s*$')) {
        $match = [regex]::Match($batch, '(?ims)^\s*(?:CREATE OR ALTER|ALTER|CREATE) PROCEDURE dbo\.(sp_\w+)\b.*')
        if ($match.Success) { $procedures[$match.Groups[1].Value] = $match.Value.Trim() }
    }
}
$names = @('sp_GetProductsPaged', 'sp_GetProductById', 'sp_GetRelatedProducts', 'sp_GetCategories', 'sp_GetBrands',
    'sp_GetInventoryByVariantId', 'sp_GetInventoryList', 'sp_GetInventoryStatusByVariantId', 'sp_GetVariantPriceInfo',
    'sp_AdminDashboard', 'sp_AdminInventoryTrend', 'sp_AdminInventoryReport', 'sp_AdminBrandInventoryDetails',
    'sp_AdminInventoryProducts', 'sp_AdminInventoryVariants', 'sp_AdminSellableVariants', 'sp_AdminCatalogProducts',
    'sp_AdminGlobalSearch', 'sp_AdminStockAuditLogs', 'sp_AdminStockHistory', 'sp_AdminRecentActivity',
    'sp_AdminVariants', 'sp_AdminColors', 'sp_AdminGetProductComplete', 'sp_AdminReviews',
    'sp_GetProductReviews', 'sp_GetProductSpecifications')
$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine(@'
-- Generated by Build-ActiveVisibilityMigration.ps1; rebuild after changing source procedures.
-- Active-only operational visibility. Historical orders/payments remain unchanged.
CREATE OR ALTER VIEW dbo.v_VisibleProducts AS
SELECT p.* FROM dbo.Products p WHERE p.IsActive = 1;
GO
CREATE OR ALTER VIEW dbo.v_VisibleProductVariants AS
SELECT v.* FROM dbo.ProductVariants v
JOIN dbo.ProductColors c ON c.Id = v.ProductColorId
JOIN dbo.v_VisibleProducts p ON p.Id = c.ProductId
WHERE v.IsActive = 1;
GO
CREATE OR ALTER VIEW dbo.v_VisibleInventories AS
SELECT i.* FROM dbo.Inventories i
JOIN dbo.v_VisibleProductVariants v ON v.Id = i.VariantId;
GO
CREATE OR ALTER VIEW dbo.v_VisibleStockAuditLogs AS
SELECT l.* FROM dbo.StockAuditLogs l
JOIN dbo.v_VisibleProductVariants v ON v.Id = l.VariantId;
GO
CREATE OR ALTER VIEW dbo.v_VisibleProductColors AS
SELECT c.* FROM dbo.ProductColors c
JOIN dbo.v_VisibleProducts p ON p.Id = c.ProductId
WHERE EXISTS (SELECT 1 FROM dbo.v_VisibleProductVariants v WHERE v.ProductColorId = c.Id);
GO
'@)
foreach ($name in $names) {
    if (-not $procedures.ContainsKey($name)) { throw "Missing procedure $name" }
    $definition = $procedures[$name]
    if ($definition -match '(?im)^\s*(INSERT|UPDATE|DELETE|MERGE)\b') { throw "Not a read-only procedure: $name" }
    $definition = [regex]::Replace($definition, '^(?:CREATE OR ALTER|ALTER|CREATE) PROCEDURE', 'CREATE OR ALTER PROCEDURE')
    if ($name -eq 'sp_GetProductReviews') {
        $definition = $definition.Replace('WHERE ProductId = @ProductId', 'WHERE ProductId = @ProductId AND EXISTS (SELECT 1 FROM dbo.Products p WHERE p.Id = @ProductId)')
    }
    foreach ($table in @('Products', 'ProductVariants', 'Inventories', 'StockAuditLogs', 'ProductColors')) {
        $definition = [regex]::Replace($definition, '\bdbo\.' + $table + '\b', 'dbo.v_Visible' + $table)
    }
    [void]$builder.AppendLine($definition)
    [void]$builder.AppendLine('GO')
}
[IO.File]::WriteAllText((Join-Path $databaseRoot 'schema/17_active_catalog_visibility.sql'), $builder.ToString(), (New-Object System.Text.UTF8Encoding($true)))
Write-Output "Generated active-only visibility for $($names.Count) read procedures."
