<#!
Build a standalone SSMS script from the canonical schema and ordered migrations.
This only writes a SQL file; it does not connect to or modify SQL Server.
!#>
[CmdletBinding()]
param(
    [ValidatePattern('^[A-Za-z][A-Za-z0-9_]{0,127}$')]
    [string]$DatabaseName = 'HelmetCartelDB'
)
$ErrorActionPreference = 'Stop'
$databaseRoot = Split-Path $PSScriptRoot -Parent
$outputPath = Join-Path $PSScriptRoot 'new_database_minimal.sql'
$files = @(
    'schema/01_schema.sql',
    'schema/03_product_gallery.sql',
    'schema/04_product_specifications.sql',
    'schema/05_product_order_count_index.sql',
    'schema/06_admin_portal_migration.sql',
    'queries/03_procedures_and_queries.sql',
    'queries/04_product_specification_procedures.sql',
    'queries/05_admin_operations.sql',
    'queries/06_admin_catalog.sql',
    'schema/08_discounts_and_search_migration.sql',
    'schema/09_inventory_audit_and_global_search.sql',
    'schema/10_product_edit_and_gallery.sql',
    'schema/11_delete_product_and_permissions.sql',
    'schema/12_update_search_and_variants.sql',
    'schema/13_dynamic_admin_metrics.sql',
    'schema/14_pos_and_inventory_drilldown.sql',
    'schema/15_catalog_enhancements.sql',
    'schema/16_pos_global_search.sql',
    'schema/17_active_catalog_visibility.sql',
    'schema/18_delivery_fulfillment_migration.sql',
    'setup/minimal_seed.sql',
    'setup/dashboard_sample_data.sql',
    'schema/19_user_profile_and_tracking_migration.sql',
    'schema/20_multi_brand_and_color_enhancement.sql',
    'schema/21_user_addresses_and_checkout_enhancement.sql',
    'schema/22_clean_schema_and_enforce_unique_phone.sql',
    'schema/23_add_recipient_contact_to_user_addresses.sql',
    'schema/24_remove_redundant_user_fullname.sql',
    'schema/25_rma_returns_and_reviews_moderation.sql',
    'schema/26_fix_quoted_identifiers.sql',
    'schema/27_sales_by_brand_and_category.sql',
    'schema/28_activity_feed_and_stock_cleanup.sql',
    'schema/29_fix_cancel_and_analytics.sql',
    'schema/30_sales_performance_analytics.sql',
    'schema/31_stock_reservation_lifecycle_fix.sql',
    'schema/32_fix_admin_catalog_drafts_visibility.sql',
    'schema/33_add_sp_get_product_by_slug.sql',
    'schema/34_fix_admin_product_draft_editing.sql',
    'schema/35_fix_draft_placeholder_images.sql',
    'schema/36_schema_enhancements_and_snapshots.sql',
    'schema/37_drop_deprecated_fields.sql',
    'schema/38_update_drafts_to_unpublished.sql',
    'schema/39_inventory_variant_active_toggle.sql',
    'schema/39_robust_product_specifications.sql',
    'schema/40_vouchers_and_receipts.sql',
    'schema/41_fix_catalog_save_pricing.sql',
    'schema/42_admin_global_search_expansion.sql',
    'schema/43_activity_feed_load_more_and_actor_role.sql'
)
$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine(@"
-- GENERATED by Build-MinimalDatabase.ps1. Edit source scripts and rebuild.
-- Run this complete file in a normal SSMS query window.
-- Stops if the database already exists. Never drops or overwrites a database.
USE [master];
GO
IF DB_ID(N'$DatabaseName') IS NOT NULL
    THROW 52091, 'Target database already exists. Choose a new database name.', 1;
GO
CREATE DATABASE [$DatabaseName];
GO
USE [$DatabaseName];
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
"@)
foreach ($relativePath in $files) {
    $source = [IO.File]::ReadAllText((Join-Path $databaseRoot $relativePath))
    if ($relativePath -eq 'schema/01_schema.sql') {
        $start = $source.IndexOf('SET ANSI_NULLS ON;')
        if ($start -lt 0) { throw 'Base schema preamble was not recognized.' }
        $source = $source.Substring($start)
    }
    # Remove fixed database context from every included source. All batches
    # must stay in the new database, including migrations with bracketed USE.
    $source = [regex]::Replace($source, '(?im)^\s*USE\s+\[?HelmetCartel(?:Minimal)?DB\]?\s*;\s*$', '')
    # Keep generated output free of trailing spaces inherited from old scripts.
    $source = [regex]::Replace($source, '(?m)[\t ]+(?=\r?$)', '')
    [void]$builder.AppendLine("-- Source: $relativePath")
    [void]$builder.AppendLine($source)
    [void]$builder.AppendLine("`nGO")
}
[IO.File]::WriteAllText($outputPath, $builder.ToString(), (New-Object System.Text.UTF8Encoding($true)))
Write-Output "Created $outputPath for $DatabaseName (5 products, 10 SKUs, 6 sample orders)."
