//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelmetCartelOrderingAndManagementSys.Admin {
    
    public partial class CatalogPage {
        
        protected global::System.Web.UI.WebControls.LinkButton btnTabAll;
        protected global::System.Web.UI.WebControls.LinkButton btnTabActive;
        protected global::System.Web.UI.WebControls.LinkButton btnTabFeatured;
        protected global::System.Web.UI.WebControls.Literal litShowingTop;
        protected global::System.Web.UI.WebControls.Literal litTotalTop;
        protected global::System.Web.UI.WebControls.Repeater rptCatalog;
        protected global::System.Web.UI.WebControls.Panel pnlCatalogPagination;
        protected global::System.Web.UI.WebControls.LinkButton lnkCatalogPrev;
        protected global::System.Web.UI.WebControls.Repeater rptCatalogPages;
        protected global::System.Web.UI.WebControls.LinkButton lnkCatalogNext;
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteProductId;
        protected global::System.Web.UI.WebControls.Button btnConfirmDeleteProduct;
        protected global::System.Web.UI.WebControls.HiddenField hdnVariantsJson;
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnEditProductId;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewBrand;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewCategory;
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtNewName;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewStyle;
        protected global::System.Web.UI.HtmlControls.HtmlTextArea txtNewDescription;
        protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl txtNewBasePrice;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewDiscountType;
        protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl txtNewDiscountValue;
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox chkNewDiscountActive;
        protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl txtNewDiscountStartDate;
        protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl txtNewDiscountEndDate;
        protected global::System.Web.UI.WebControls.FileUpload fileUploadImages;
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtNewImageUrl;
        protected global::System.Web.UI.HtmlControls.HtmlTextArea txtNewGalleryUrls;
        protected global::System.Web.UI.WebControls.Button btnSubmitNewProduct;
    }
}
