//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelmetCartelOrderingAndManagementSys.Admin
{
    public partial class CatalogItemPage
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl txtHeaderTitle;
        protected global::System.Web.UI.WebControls.LinkButton btnSaveDraft;
        protected global::System.Web.UI.WebControls.LinkButton btnPublish;
        protected global::System.Web.UI.WebControls.HiddenField hdnProductId;
        protected global::System.Web.UI.WebControls.HiddenField hdnIsActive;
        protected global::System.Web.UI.WebControls.HiddenField hdnDiscountType;
        protected global::System.Web.UI.WebControls.HiddenField hdnDiscountIsActive;
        protected global::System.Web.UI.WebControls.HiddenField hdnColorType;
        protected global::System.Web.UI.WebControls.HiddenField hdnColorsJson;
        protected global::System.Web.UI.WebControls.HiddenField hdnVariantsJson;
        protected global::System.Web.UI.WebControls.HiddenField hdnSpecificationsJson;
        protected global::System.Web.UI.WebControls.HiddenField hdnGalleryJson;
        protected global::System.Web.UI.WebControls.HiddenField hdnRedirectAfterSave;
        protected global::System.Web.UI.WebControls.DropDownList ddlBrand;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.TextBox txtProductName;
        protected global::System.Web.UI.WebControls.TextBox txtSlug;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.CheckBox chkIsFeatured;
        protected global::System.Web.UI.WebControls.TextBox txtBasePrice;
        protected global::System.Web.UI.WebControls.TextBox txtDiscountValue;
        protected global::System.Web.UI.WebControls.DropDownList ddlDiscountUnit;
        protected global::System.Web.UI.WebControls.TextBox txtDiscountStartDate;
        protected global::System.Web.UI.WebControls.TextBox txtDiscountEndDate;
        protected global::System.Web.UI.WebControls.TextBox txtMainImageUrl;
    }
}
