//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelmetCartelOrderingAndManagementSys.Admin {
    
    public partial class InventoryPage {
        
        protected global::System.Web.UI.WebControls.LinkButton btnViewActiveStock;
        protected global::System.Web.UI.WebControls.LinkButton btnViewAuditHistory;
        protected global::System.Web.UI.WebControls.Panel pnlActiveStock;
        protected global::System.Web.UI.WebControls.LinkButton btnTabAll;
        protected global::System.Web.UI.WebControls.LinkButton btnTabInStock;
        protected global::System.Web.UI.WebControls.LinkButton btnTabLowStock;
        protected global::System.Web.UI.WebControls.LinkButton btnTabOutOfStock;
        protected global::System.Web.UI.WebControls.DropDownList ddlBrandFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoryFilter;
        protected global::System.Web.UI.WebControls.Literal litAvailableCount;
        protected global::System.Web.UI.WebControls.Repeater rptInventory;
        protected global::System.Web.UI.WebControls.Literal litShowingRange;
        protected global::System.Web.UI.WebControls.Literal litTotalCount;
        protected global::System.Web.UI.WebControls.Panel pnlInventoryPagination;
        protected global::System.Web.UI.WebControls.LinkButton btnPrevPage;
        protected global::System.Web.UI.WebControls.Repeater rptPaginationPages;
        protected global::System.Web.UI.WebControls.LinkButton btnNextPage;
        protected global::System.Web.UI.WebControls.Panel pnlAuditHistory;
        protected global::System.Web.UI.WebControls.LinkButton btnAuditTypeAll;
        protected global::System.Web.UI.WebControls.LinkButton btnAuditTypeRestock;
        protected global::System.Web.UI.WebControls.LinkButton btnAuditTypeAdjustment;
        protected global::System.Web.UI.WebControls.DropDownList ddlAuditBrandFilter;
        protected global::System.Web.UI.WebControls.Literal litAuditCount;
        protected global::System.Web.UI.WebControls.Literal litAuditUnitsAdded;
        protected global::System.Web.UI.WebControls.Repeater rptAuditHistory;

        /// <summary>
        /// pnlAuditPagination control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAuditPagination;

        /// <summary>
        /// btnAuditPrevPage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAuditPrevPage;

        /// <summary>
        /// rptAuditPaginationPages control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAuditPaginationPages;

        /// <summary>
        /// btnAuditNextPage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAuditNextPage;
        protected global::System.Web.UI.WebControls.HiddenField hdnAdjustVariantId;
        protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl txtAdjustQuantity;
        protected global::System.Web.UI.WebControls.DropDownList ddlAdjustReason;
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtAdjustReference;
        protected global::System.Web.UI.WebControls.Button btnSubmitStockAdjust;
    }
}
