//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelmetCartelOrderingAndManagementSys.Admin {
    
    public partial class OrdersPage {
        
        protected global::System.Web.UI.WebControls.LinkButton btnTabAll;
        protected global::System.Web.UI.WebControls.LinkButton btnTabProcessing;
        protected global::System.Web.UI.WebControls.LinkButton btnTabReady;
        protected global::System.Web.UI.WebControls.LinkButton btnTabShipped;
        protected global::System.Web.UI.WebControls.LinkButton btnTabCompleted;
        protected global::System.Web.UI.WebControls.LinkButton btnTabPending;
        protected global::System.Web.UI.WebControls.TextBox txtOrderDate;
        protected global::System.Web.UI.WebControls.Button btnApplyDateFilter;
        protected global::System.Web.UI.WebControls.Literal litShowingTop;
        protected global::System.Web.UI.WebControls.Literal litTotalTop;
        protected global::System.Web.UI.WebControls.Repeater rptOrders;
        protected global::System.Web.UI.WebControls.Panel pnlOrdersPagination;
        protected global::System.Web.UI.WebControls.LinkButton lnkOrdersPrev;
        protected global::System.Web.UI.WebControls.Repeater rptOrdersPages;
        protected global::System.Web.UI.WebControls.LinkButton lnkOrdersNext;
    }
}
