//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelmetCartelOrderingAndManagementSys.Admin {
    
    public partial class CatalogPage {
        
        protected global::System.Web.UI.WebControls.LinkButton btnTabAll;
        protected global::System.Web.UI.WebControls.LinkButton btnTabActive;
        protected global::System.Web.UI.WebControls.LinkButton btnTabDrafts;
        protected global::System.Web.UI.WebControls.LinkButton btnTabFeatured;
        protected global::System.Web.UI.WebControls.Literal litShowingTop;
        protected global::System.Web.UI.WebControls.Literal litTotalTop;
        protected global::System.Web.UI.WebControls.Repeater rptCatalog;
        protected global::System.Web.UI.WebControls.Panel pnlCatalogPagination;
        protected global::System.Web.UI.WebControls.LinkButton lnkCatalogPrev;
        protected global::System.Web.UI.WebControls.Repeater rptCatalogPages;
        protected global::System.Web.UI.WebControls.LinkButton lnkCatalogNext;
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteProductId;
        protected global::System.Web.UI.WebControls.Button btnConfirmDeleteProduct;
    }
}
