//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelmetCartelOrderingAndManagementSys.Admin {
    
    public partial class UsersPage {
        
        protected global::System.Web.UI.WebControls.LinkButton btnTabAll;
        protected global::System.Web.UI.WebControls.LinkButton btnTabAdmin;
        protected global::System.Web.UI.WebControls.LinkButton btnTabStaff;
        protected global::System.Web.UI.WebControls.LinkButton btnTabCustomer;
        protected global::System.Web.UI.WebControls.Literal litShowingTop;
        protected global::System.Web.UI.WebControls.Literal litTotalTop;
        protected global::System.Web.UI.WebControls.Repeater rptUsers;
        protected global::System.Web.UI.WebControls.Panel pnlUsersPagination;
        protected global::System.Web.UI.WebControls.LinkButton lnkUsersPrev;
        protected global::System.Web.UI.WebControls.Repeater rptUsersPages;
        protected global::System.Web.UI.WebControls.LinkButton lnkUsersNext;
    }
}
