//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelmetCartelOrderingAndManagementSys.Pages.Admin.Orders
{
    public partial class OrderDetail
    {
        protected global::System.Web.UI.WebControls.Literal litOrderNumberTitle;
        protected global::System.Web.UI.WebControls.Literal litHeaderBadges;
        protected global::System.Web.UI.WebControls.Literal litCreatedAt;
        protected global::System.Web.UI.WebControls.Literal litOrderSource;
        protected global::System.Web.UI.WebControls.Literal litActionButtons;
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlOrderContent;
        protected global::System.Web.UI.WebControls.Literal litKpiDeliveryMethod;
        protected global::System.Web.UI.WebControls.Literal litKpiDeliveryCity;
        protected global::System.Web.UI.WebControls.Literal litKpiPaymentStatus;
        protected global::System.Web.UI.WebControls.Literal litKpiPaymentMethod;
        protected global::System.Web.UI.WebControls.Literal litKpiOrderStatus;
        protected global::System.Web.UI.WebControls.Literal litKpiOrderDate;
        protected global::System.Web.UI.WebControls.Literal litKpiOrderTime;
        protected global::System.Web.UI.WebControls.Literal litItemCount;
        protected global::System.Web.UI.WebControls.Repeater rptOrderItems;
        protected global::System.Web.UI.WebControls.Literal litSubtotal;
        protected global::System.Web.UI.WebControls.Literal litDeliveryFee;
        protected global::System.Web.UI.WebControls.PlaceHolder phDiscount;
        protected global::System.Web.UI.WebControls.Literal litDiscount;
        protected global::System.Web.UI.WebControls.Literal litTotalAmount;
        protected global::System.Web.UI.WebControls.PlaceHolder phNotes;
        protected global::System.Web.UI.WebControls.Literal litDeliveryNotes;
        protected global::System.Web.UI.WebControls.Literal litCustomerName;
        protected global::System.Web.UI.WebControls.Literal litCustomerEmail;
        protected global::System.Web.UI.WebControls.Literal litCustomerPhone;
        protected global::System.Web.UI.WebControls.Literal litDeliveryMethod;
        protected global::System.Web.UI.WebControls.PlaceHolder phDeliveryAddress;
        protected global::System.Web.UI.WebControls.Literal litFullAddress;
        protected global::System.Web.UI.WebControls.Literal litDeliveryRegion;
        protected global::System.Web.UI.WebControls.PlaceHolder phCourierInfo;
        protected global::System.Web.UI.WebControls.Literal litCourier;
        protected global::System.Web.UI.WebControls.Literal litTrackingNumber;
        protected global::System.Web.UI.WebControls.Literal litPaymentMethod;
        protected global::System.Web.UI.WebControls.Literal litPaymentStatus;
        protected global::System.Web.UI.WebControls.TextBox txtCourier;
        protected global::System.Web.UI.WebControls.TextBox txtTrackingNumber;
        protected global::System.Web.UI.WebControls.Button btnConfirmDispatch;
        protected global::System.Web.UI.WebControls.Literal litSummaryItemCount;
        protected global::System.Web.UI.WebControls.Literal litPaidAmountText;
        protected global::System.Web.UI.WebControls.Literal litCustomerChannel;
        protected global::System.Web.UI.WebControls.Literal litShippingSectionTitle;
        protected global::System.Web.UI.WebControls.Literal litShippingRecipient;
    }
}
