//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelmetCartelOrderingAndManagementSys.Admin {
    
    public partial class ReportsPage {
        
        protected global::System.Web.UI.WebControls.Button btnExportExcel;
        protected global::System.Web.UI.WebControls.LinkButton btnPresetToday;
        protected global::System.Web.UI.WebControls.LinkButton btnPresetWeek;
        protected global::System.Web.UI.WebControls.LinkButton btnPresetMonth;
        protected global::System.Web.UI.WebControls.LinkButton btnPreset30Days;
        protected global::System.Web.UI.WebControls.LinkButton btnPresetCustom;
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;
        protected global::System.Web.UI.WebControls.Button btnApplyDateFilter;
        protected global::System.Web.UI.WebControls.Panel pnlDateError;
        protected global::System.Web.UI.WebControls.Literal litDateErrorMessage;
        protected global::System.Web.UI.WebControls.Literal litTotalRevenue;
        protected global::System.Web.UI.WebControls.Literal litTotalRevenueTrend;
        protected global::System.Web.UI.WebControls.Literal litRevenueSubtitle;
        protected global::System.Web.UI.WebControls.Literal litTotalOrders;
        protected global::System.Web.UI.WebControls.Literal litTotalOrdersTrend;
        protected global::System.Web.UI.WebControls.Literal litAverageOrderValue;
        protected global::System.Web.UI.WebControls.Literal litAovTrend;
        protected global::System.Web.UI.WebControls.Literal litTotalUnits;
        protected global::System.Web.UI.WebControls.Literal litTotalUnitsTrend;
        protected global::System.Web.UI.WebControls.Literal litTotalVariants;
        protected global::System.Web.UI.WebControls.Literal litTotalVariantsTrend;
        protected global::System.Web.UI.WebControls.Repeater rptDailySales;
        protected global::System.Web.UI.WebControls.Panel pnlDailySalesPagination;
        protected global::System.Web.UI.WebControls.LinkButton lnkDailySalesPrev;
        protected global::System.Web.UI.WebControls.Repeater rptDailySalesPages;
        protected global::System.Web.UI.WebControls.LinkButton lnkDailySalesNext;
        protected global::System.Web.UI.WebControls.Repeater rptBrandReport;
        protected global::System.Web.UI.WebControls.Panel pnlBrandReportPagination;
        protected global::System.Web.UI.WebControls.LinkButton lnkBrandReportPrev;
        protected global::System.Web.UI.WebControls.Repeater rptBrandReportPages;
        protected global::System.Web.UI.WebControls.LinkButton lnkBrandReportNext;
    }
}
