-- Generated by Build-ActiveVisibilityMigration.ps1; rebuild after changing source procedures.
-- Active-only operational visibility. Historical orders/payments remain unchanged.
CREATE OR ALTER VIEW dbo.v_VisibleProducts AS
SELECT p.* FROM dbo.Products p WHERE p.IsActive = 1;
GO
CREATE OR ALTER VIEW dbo.v_VisibleProductVariants AS
SELECT v.* FROM dbo.ProductVariants v
JOIN dbo.ProductColors c ON c.Id = v.ProductColorId
JOIN dbo.v_VisibleProducts p ON p.Id = c.ProductId
WHERE v.IsActive = 1;
GO
CREATE OR ALTER VIEW dbo.v_VisibleInventories AS
SELECT i.* FROM dbo.Inventories i
JOIN dbo.v_VisibleProductVariants v ON v.Id = i.VariantId;
GO
CREATE OR ALTER VIEW dbo.v_VisibleStockAuditLogs AS
SELECT l.* FROM dbo.StockAuditLogs l
JOIN dbo.v_VisibleProductVariants v ON v.Id = l.VariantId;
GO
CREATE OR ALTER VIEW dbo.v_VisibleProductColors AS
SELECT c.* FROM dbo.ProductColors c
JOIN dbo.v_VisibleProducts p ON p.Id = c.ProductId
WHERE EXISTS (SELECT 1 FROM dbo.v_VisibleProductVariants v WHERE v.ProductColorId = c.Id);
GO
CREATE OR ALTER PROCEDURE dbo.sp_GetProductsPaged
    @CategoryId INT = NULL,
    @BrandId INT = NULL,
    @Brand NVARCHAR(100) = NULL,
    @Category NVARCHAR(100) = NULL,
    @RidingStyle NVARCHAR(50) = NULL,
    @Search NVARCHAR(200) = NULL,
    @OnSale BIT = 0,
    @MinPrice DECIMAL(18,2) = NULL,
    @MaxPrice DECIMAL(18,2) = NULL,
    @Colors NVARCHAR(200) = NULL,
    @Sizes NVARCHAR(100) = NULL,
    @SortBy NVARCHAR(50) = 'popular',
    @PageNumber INT = 1,
    @PageSize INT = 9,
    @TotalCount INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    SET @Search = NULLIF(LTRIM(RTRIM(@Search)), N'');
    SET @Colors = NULLIF(LTRIM(RTRIM(@Colors)), N'');
    SET @Sizes = NULLIF(LTRIM(RTRIM(@Sizes)), N'');
    IF @PageNumber IS NULL OR @PageNumber < 1 SET @PageNumber = 1;
    IF @PageSize IS NULL OR @PageSize < 1 SET @PageSize = 9;
    IF @PageSize > 100 SET @PageSize = 100;

    DECLARE @Now DATETIME2 = SYSUTCDATETIME();

    -- Calculate total count
    SELECT @TotalCount = COUNT(*)
    FROM dbo.v_VisibleProducts p
    INNER JOIN dbo.Brands b ON p.BrandId = b.Id
    INNER JOIN dbo.Categories c ON p.CategoryId = c.Id
    WHERE p.IsActive = 1
      AND (
          ISNULL(@OnSale, 0) = 0 
          OR (
              (p.DiscountPercentage > 0 OR (p.DiscountType = N'FIXED_AMOUNT' AND p.DiscountAmount > 0))
              AND ISNULL(p.DiscountIsActive, 1) = 1
              AND (p.DiscountStartDate IS NULL OR p.DiscountStartDate <= @Now)
              AND (p.DiscountEndDate IS NULL OR p.DiscountEndDate >= @Now)
          )
      )
      AND (@CategoryId IS NULL OR p.CategoryId = @CategoryId)
      AND (@BrandId IS NULL OR p.BrandId = @BrandId)
      AND (@Brand IS NULL OR @Brand = 'all' OR b.Name = @Brand)
      AND (@Category IS NULL OR @Category = 'all' OR c.Slug = @Category OR c.Name LIKE '%' + @Category + '%')
      AND (@RidingStyle IS NULL OR @RidingStyle = 'all' OR p.RidingStyle = @RidingStyle)
      AND (
          @Search IS NULL 
          OR p.Name LIKE N'%' + @Search + N'%'
          OR b.Name LIKE N'%' + @Search + N'%'
          OR c.Name LIKE N'%' + @Search + N'%'
          OR p.RidingStyle LIKE N'%' + @Search + N'%'
          OR p.Description LIKE N'%' + @Search + N'%'
          OR EXISTS (
              SELECT 1 
              FROM dbo.v_VisibleProductColors pc_s
              JOIN dbo.v_VisibleProductVariants pv_s ON pv_s.ProductColorId = pc_s.Id
              WHERE pc_s.ProductId = p.Id AND pv_s.SKU LIKE N'%' + @Search + N'%'
          )
      )
      AND (@MinPrice IS NULL OR dbo.fn_CalculateEffectivePrice(p.BasePrice, 0, p.DiscountPercentage, p.DiscountType, p.DiscountAmount, p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive) >= @MinPrice)
      AND (@MaxPrice IS NULL OR dbo.fn_CalculateEffectivePrice(p.BasePrice, 0, p.DiscountPercentage, p.DiscountType, p.DiscountAmount, p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive) <= @MaxPrice)
      AND EXISTS
      (
          SELECT 1
          FROM dbo.v_VisibleProductColors pc
          JOIN dbo.v_VisibleProductVariants pv ON pv.ProductColorId = pc.Id
          WHERE pc.ProductId = p.Id AND pv.IsActive = 1
            AND (@Colors IS NULL OR CHARINDEX(N',' + UPPER(dbo.fn_BaseColorFromHex(pc.ColorHex)) + N',', N',' + UPPER(@Colors) + N',') > 0)
            AND (@Sizes IS NULL OR CHARINDEX(N',' + UPPER(pv.Size) + N',', N',' + UPPER(@Sizes) + N',') > 0)
      );

    -- Paged rows
    SELECT 
        p.Id,
        p.Name,
        p.Slug,
        b.Name AS Brand,
        c.Name AS Category,
        p.RidingStyle,
        p.BasePrice,
        p.DiscountPercentage,
        p.DiscountType,
        p.DiscountAmount,
        p.DiscountStartDate,
        p.DiscountEndDate,
        CASE 
            WHEN ISNULL(p.DiscountIsActive, 1) = 1 
                 AND (p.DiscountStartDate IS NULL OR p.DiscountStartDate <= @Now)
                 AND (p.DiscountEndDate IS NULL OR p.DiscountEndDate >= @Now)
                 AND (p.DiscountPercentage > 0 OR (p.DiscountType = N'FIXED_AMOUNT' AND p.DiscountAmount > 0))
            THEN 1 
            ELSE 0 
        END AS IsDiscountActive,
        dbo.fn_CalculateEffectivePrice(p.BasePrice, 0, p.DiscountPercentage, p.DiscountType, p.DiscountAmount, p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive) AS EffectivePrice,
        review.Rating,
        review.ReviewCount,
        p.MainImageUrl,
        p.Description,
        p.IsFeatured
    FROM dbo.v_VisibleProducts p
    INNER JOIN dbo.Brands b ON p.BrandId = b.Id
    INNER JOIN dbo.Categories c ON p.CategoryId = c.Id
    OUTER APPLY (
        SELECT CAST(COALESCE(AVG(CAST(r.Rating AS DECIMAL(9,2))), 0) AS DECIMAL(3,2)) AS Rating,
               COUNT(*) AS ReviewCount
        FROM dbo.ProductReviews r
        WHERE r.ProductId = p.Id AND r.IsHidden = 0
    ) review
    WHERE p.IsActive = 1
      AND (
          ISNULL(@OnSale, 0) = 0 
          OR (
              (p.DiscountPercentage > 0 OR (p.DiscountType = N'FIXED_AMOUNT' AND p.DiscountAmount > 0))
              AND ISNULL(p.DiscountIsActive, 1) = 1
              AND (p.DiscountStartDate IS NULL OR p.DiscountStartDate <= @Now)
              AND (p.DiscountEndDate IS NULL OR p.DiscountEndDate >= @Now)
          )
      )
      AND (@CategoryId IS NULL OR p.CategoryId = @CategoryId)
      AND (@BrandId IS NULL OR p.BrandId = @BrandId)
      AND (@Brand IS NULL OR @Brand = 'all' OR b.Name = @Brand)
      AND (@Category IS NULL OR @Category = 'all' OR c.Slug = @Category OR c.Name LIKE '%' + @Category + '%')
      AND (@RidingStyle IS NULL OR @RidingStyle = 'all' OR p.RidingStyle = @RidingStyle)
      AND (
          @Search IS NULL 
          OR p.Name LIKE N'%' + @Search + N'%'
          OR b.Name LIKE N'%' + @Search + N'%'
          OR c.Name LIKE N'%' + @Search + N'%'
          OR p.RidingStyle LIKE N'%' + @Search + N'%'
          OR p.Description LIKE N'%' + @Search + N'%'
          OR EXISTS (
              SELECT 1 
              FROM dbo.v_VisibleProductColors pc_s
              JOIN dbo.v_VisibleProductVariants pv_s ON pv_s.ProductColorId = pc_s.Id
              WHERE pc_s.ProductId = p.Id AND pv_s.SKU LIKE N'%' + @Search + N'%'
          )
      )
      AND (@MinPrice IS NULL OR dbo.fn_CalculateEffectivePrice(p.BasePrice, 0, p.DiscountPercentage, p.DiscountType, p.DiscountAmount, p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive) >= @MinPrice)
      AND (@MaxPrice IS NULL OR dbo.fn_CalculateEffectivePrice(p.BasePrice, 0, p.DiscountPercentage, p.DiscountType, p.DiscountAmount, p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive) <= @MaxPrice)
      AND EXISTS
      (
          SELECT 1
          FROM dbo.v_VisibleProductColors pc
          JOIN dbo.v_VisibleProductVariants pv ON pv.ProductColorId = pc.Id
          WHERE pc.ProductId = p.Id AND pv.IsActive = 1
            AND (@Colors IS NULL OR CHARINDEX(N',' + UPPER(dbo.fn_BaseColorFromHex(pc.ColorHex)) + N',', N',' + UPPER(@Colors) + N',') > 0)
            AND (@Sizes IS NULL OR CHARINDEX(N',' + UPPER(pv.Size) + N',', N',' + UPPER(@Sizes) + N',') > 0)
      )
    ORDER BY 
        CASE WHEN @SortBy = 'price_asc' THEN dbo.fn_CalculateEffectivePrice(p.BasePrice, 0, p.DiscountPercentage, p.DiscountType, p.DiscountAmount, p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive) END ASC,
        CASE WHEN @SortBy = 'price_desc' THEN dbo.fn_CalculateEffectivePrice(p.BasePrice, 0, p.DiscountPercentage, p.DiscountType, p.DiscountAmount, p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive) END DESC,
        CASE WHEN @SortBy = 'newest' THEN p.CreatedAt END DESC,
        CASE WHEN @SortBy = 'rating' THEN review.Rating END DESC,
        CASE WHEN @SortBy = 'popular' OR @SortBy IS NULL THEN review.ReviewCount END DESC,
        p.Id ASC
    OFFSET (@PageNumber - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_GetProductById
    @Id INT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Now DATETIME2 = SYSUTCDATETIME();

    -- Result Set 1: Product Header
    SELECT 
        p.Id,
        p.Name,
        p.Slug,
        b.Name AS Brand,
        c.Name AS Category,
        p.RidingStyle,
        p.BasePrice,
        p.DiscountPercentage,
        p.DiscountType,
        p.DiscountAmount,
        p.DiscountStartDate,
        p.DiscountEndDate,
        CASE 
            WHEN ISNULL(p.DiscountIsActive, 1) = 1 
                 AND (p.DiscountStartDate IS NULL OR p.DiscountStartDate <= @Now)
                 AND (p.DiscountEndDate IS NULL OR p.DiscountEndDate >= @Now)
                 AND (p.DiscountPercentage > 0 OR (p.DiscountType = N'FIXED_AMOUNT' AND p.DiscountAmount > 0))
            THEN 1 
            ELSE 0 
        END AS IsDiscountActive,
        dbo.fn_CalculateEffectivePrice(p.BasePrice, 0, p.DiscountPercentage, p.DiscountType, p.DiscountAmount, p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive) AS EffectivePrice,
        review.Rating,
        review.ReviewCount,
        orders.OrderCount,
        p.MainImageUrl,
        p.Description,
        p.IsFeatured
    FROM dbo.v_VisibleProducts p
    INNER JOIN dbo.Brands b ON p.BrandId = b.Id
    INNER JOIN dbo.Categories c ON p.CategoryId = c.Id
    OUTER APPLY (
        SELECT CAST(COALESCE(AVG(CAST(r.Rating AS DECIMAL(9,2))), 0) AS DECIMAL(3,2)) AS Rating,
               COUNT(*) AS ReviewCount
        FROM dbo.ProductReviews r
        WHERE r.ProductId = p.Id AND r.IsHidden = 0
    ) review
    OUTER APPLY (
        SELECT COUNT(DISTINCT oi.OrderId) AS OrderCount
        FROM dbo.v_VisibleProductColors pc
        INNER JOIN dbo.v_VisibleProductVariants pv ON pv.ProductColorId = pc.Id
        INNER JOIN dbo.OrderItems oi ON oi.VariantId = pv.Id
        INNER JOIN dbo.Orders o ON o.Id = oi.OrderId
        WHERE pc.ProductId = p.Id AND o.Status <> N'Cancelled'
    ) orders
    WHERE p.Id = @Id AND p.IsActive = 1;

    -- Result Set 2: Variants & Stock
    SELECT 
        pv.Id,
        pc.ProductId,
        pv.SKU,
        pv.Size,
        pc.Color,
        pc.ColorHex,
        pv.PriceAdjustment,
        dbo.fn_CalculateEffectivePrice(p.BasePrice, pv.PriceAdjustment, p.DiscountPercentage, p.DiscountType, p.DiscountAmount, p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive) AS EffectivePrice,
        ISNULL(i.CurrentStock, 0) AS CurrentStock,
        ISNULL(i.IsLowStock, 0) AS IsLowStock
    FROM dbo.v_VisibleProductVariants pv
    INNER JOIN dbo.v_VisibleProductColors pc ON pv.ProductColorId = pc.Id
    INNER JOIN dbo.v_VisibleProducts p ON pc.ProductId = p.Id
    LEFT JOIN dbo.v_VisibleInventories i ON pv.Id = i.VariantId
    WHERE pc.ProductId = @Id AND pv.IsActive = 1
    ORDER BY pv.Id ASC;

    -- Result Set 3: Additional product gallery images
    SELECT
        ImageUrl,
        COALESCE(AltText, N'Product view') AS AltText,
        CAST(DisplayOrder AS INT) AS DisplayOrder
    FROM dbo.ProductGalleryImages
    WHERE ProductId = @Id AND IsActive = 1
    ORDER BY DisplayOrder ASC, Id ASC;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_GetRelatedProducts
    @ProductId INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT TOP (4)
        p.Id,
        p.Name,
        p.Slug,
        b.Name AS Brand,
        c.Name AS Category,
        p.RidingStyle,
        p.BasePrice,
        p.DiscountPercentage,
        CAST(p.BasePrice * (1.0 - p.DiscountPercentage / 100.0) AS DECIMAL(18,2)) AS EffectivePrice,
        review.Rating,
        review.ReviewCount,
        p.MainImageUrl,
        p.Description,
        p.IsFeatured
    FROM dbo.v_VisibleProducts sourceProduct
    INNER JOIN dbo.v_VisibleProducts p ON p.Id <> sourceProduct.Id AND p.IsActive = 1
    INNER JOIN dbo.Brands b ON b.Id = p.BrandId
    INNER JOIN dbo.Categories c ON c.Id = p.CategoryId
    OUTER APPLY (
        SELECT CAST(COALESCE(AVG(CAST(r.Rating AS DECIMAL(9,2))), 0) AS DECIMAL(3,2)) AS Rating,
               COUNT(*) AS ReviewCount
        FROM dbo.ProductReviews r
        WHERE r.ProductId = p.Id AND r.IsHidden = 0
    ) review
    WHERE sourceProduct.Id = @ProductId AND sourceProduct.IsActive = 1
      AND EXISTS (
          SELECT 1 FROM dbo.v_VisibleProductColors pc
          INNER JOIN dbo.v_VisibleProductVariants pv ON pv.ProductColorId = pc.Id
          WHERE pc.ProductId = p.Id AND pv.IsActive = 1
      )
    ORDER BY CASE
                 WHEN p.CategoryId = sourceProduct.CategoryId THEN 0
                 WHEN p.RidingStyle = sourceProduct.RidingStyle THEN 1
                 ELSE 2
             END,
             review.Rating DESC,
             review.ReviewCount DESC,
             p.CreatedAt DESC,
             p.Id ASC;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_GetCategories
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        c.Id,
        c.Name,
        c.Slug,
        c.Description,
        c.DisplayOrder,
        COUNT(p.Id) AS ProductCount
    FROM dbo.Categories c
    LEFT JOIN dbo.v_VisibleProducts p ON c.Id = p.CategoryId AND p.IsActive = 1
        AND EXISTS (
            SELECT 1 FROM dbo.v_VisibleProductColors pc
            JOIN dbo.v_VisibleProductVariants pv ON pv.ProductColorId = pc.Id
            WHERE pc.ProductId = p.Id AND pv.IsActive = 1
        )
    GROUP BY c.Id, c.Name, c.Slug, c.Description, c.DisplayOrder
    ORDER BY c.DisplayOrder ASC;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_GetBrands
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        b.Id,
        b.Name,
        b.LogoUrl,
        b.Website,
        COUNT(p.Id) AS ProductCount
    FROM dbo.Brands b
    LEFT JOIN dbo.v_VisibleProducts p ON b.Id = p.BrandId AND p.IsActive = 1
        AND EXISTS (
            SELECT 1 FROM dbo.v_VisibleProductColors pc
            JOIN dbo.v_VisibleProductVariants pv ON pv.ProductColorId = pc.Id
            WHERE pc.ProductId = p.Id AND pv.IsActive = 1
        )
    WHERE b.IsActive = 1
    GROUP BY b.Id, b.Name, b.LogoUrl, b.Website
    HAVING COUNT(p.Id) > 0
    ORDER BY b.Name ASC;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_GetInventoryByVariantId
    @VariantId INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        i.Id,
        i.VariantId,
        i.CurrentStock,
        i.ReservedStock,
        i.ReorderPoint,
        i.IsLowStock,
        i.LastRestockedAt,
        i.UpdatedAt
    FROM dbo.v_VisibleInventories i
    WHERE i.VariantId = @VariantId;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_GetInventoryList
    @LowStockOnly BIT = 0,
    @Search NVARCHAR(200) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        i.Id AS InventoryId,
        pv.Id AS VariantId,
        p.Name AS ProductName,
        b.Name AS Brand,
        pv.SKU,
        pv.Size,
        pc.Color,
        i.CurrentStock,
        i.ReservedStock,
        i.ReorderPoint,
        i.IsLowStock,
        i.LastRestockedAt
    FROM dbo.v_VisibleInventories i
    INNER JOIN dbo.v_VisibleProductVariants pv ON i.VariantId = pv.Id
    INNER JOIN dbo.v_VisibleProductColors pc ON pv.ProductColorId = pc.Id
    INNER JOIN dbo.v_VisibleProducts p ON pc.ProductId = p.Id
    INNER JOIN dbo.Brands b ON p.BrandId = b.Id
    WHERE (@LowStockOnly = 0 OR i.IsLowStock = 1)
      AND (@Search IS NULL OR p.Name LIKE '%' + @Search + '%' OR pv.SKU LIKE '%' + @Search + '%')
    ORDER BY i.IsLowStock DESC, i.CurrentStock ASC;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_GetInventoryStatusByVariantId
    @VariantId INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        i.Id AS InventoryId,
        pv.Id AS VariantId,
        p.Name AS ProductName,
        b.Name AS Brand,
        pv.SKU,
        pv.Size,
        pc.Color,
        i.CurrentStock,
        i.ReservedStock,
        i.ReorderPoint,
        i.IsLowStock,
        i.LastRestockedAt
    FROM dbo.v_VisibleInventories i
    INNER JOIN dbo.v_VisibleProductVariants pv ON i.VariantId = pv.Id
    INNER JOIN dbo.v_VisibleProductColors pc ON pv.ProductColorId = pc.Id
    INNER JOIN dbo.v_VisibleProducts p ON pc.ProductId = p.Id
    INNER JOIN dbo.Brands b ON p.BrandId = b.Id
    WHERE pv.Id = @VariantId;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_GetVariantPriceInfo
    @VariantId INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        pv.Id AS VariantId,
        pc.ProductId,
        p.Name AS ProductName,
        pv.SKU,
        pv.Size,
        pc.Color,
        CAST((p.BasePrice + pv.PriceAdjustment) * (1.0 - (p.DiscountPercentage / 100.0)) AS DECIMAL(18,2)) AS UnitPrice
    FROM dbo.v_VisibleProductVariants pv
    INNER JOIN dbo.v_VisibleProductColors pc ON pv.ProductColorId = pc.Id
    INNER JOIN dbo.v_VisibleProducts p ON pc.ProductId = p.Id
    WHERE pv.Id = @VariantId AND pv.IsActive = 1 AND p.IsActive = 1;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminDashboard
    @IncludeRevenue BIT = 0
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @TodayStart DATETIME2 = CONVERT(DATETIME2, CONVERT(DATE, SYSUTCDATETIME()));
    DECLARE @YesterdayStart DATETIME2 = DATEADD(DAY, -1, @TodayStart);

    ;WITH StockAtTodayStart AS
    (
        SELECT
            i.Id,
            i.ReservedStock,
            i.ReorderPoint,
            CASE
                WHEN v.CreatedAt >= @TodayStart THEN 0
                ELSE i.CurrentStock - ISNULL(SUM(CASE WHEN l.CreatedAt >= @TodayStart THEN l.QuantityChanged ELSE 0 END), 0)
            END AS PreviousStock
        FROM dbo.v_VisibleInventories i
        JOIN dbo.v_VisibleProductVariants v ON v.Id = i.VariantId
        LEFT JOIN dbo.v_VisibleStockAuditLogs l ON l.VariantId = i.VariantId
        GROUP BY i.Id, i.CurrentStock, i.ReservedStock, i.ReorderPoint, v.CreatedAt
    )
    SELECT
        (SELECT ISNULL(SUM(CurrentStock), 0) FROM dbo.v_VisibleInventories) AS OnHandStock,
        (SELECT ISNULL(SUM(CurrentStock - ReservedStock), 0) FROM dbo.v_VisibleInventories) AS AvailableStock,
        (SELECT COUNT(*) FROM dbo.v_VisibleInventories WHERE IsLowStock = 1) AS LowStockCount,
        (SELECT COUNT(*) FROM dbo.v_VisibleInventories WHERE CurrentStock - ReservedStock = 0) AS OutOfStockCount,
        (SELECT COUNT(*) FROM dbo.Orders WHERE Status IN (N'PendingPayment', N'Processing', N'ReadyForPickup')) AS ActiveOrders,
        (SELECT ISNULL(SUM(PreviousStock), 0) FROM StockAtTodayStart) AS YesterdayOnHandStock,
        (SELECT ISNULL(SUM(CASE WHEN PreviousStock > ReservedStock THEN PreviousStock - ReservedStock ELSE 0 END), 0)
         FROM StockAtTodayStart) AS YesterdayAvailableStock,
        (SELECT COUNT(*) FROM StockAtTodayStart WHERE PreviousStock > 0 AND PreviousStock - ReservedStock <= ReorderPoint) AS YesterdayLowStockCount,
        (SELECT COUNT(*) FROM dbo.Orders WHERE CreatedAt >= @YesterdayStart AND CreatedAt < @TodayStart) AS YesterdayOrdersCount,
        CASE WHEN @IncludeRevenue = 1 THEN
            (SELECT ISNULL(SUM(Amount), 0) FROM dbo.Payments
             WHERE Status = N'Completed' AND PaidAt >= @TodayStart)
        ELSE NULL END AS TodayRevenue,
        CASE WHEN @IncludeRevenue = 1 THEN
            (SELECT ISNULL(SUM(Amount), 0) FROM dbo.Payments
             WHERE Status = N'Completed' AND PaidAt >= @YesterdayStart AND PaidAt < @TodayStart)
        ELSE NULL END AS YesterdayRevenue;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminInventoryTrend
    @StartDate DATETIME2,
    @EndDate DATETIME2
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @StartCutoff DATETIME2 = CONVERT(DATETIME2, CONVERT(DATE, @StartDate));
    DECLARE @EndExclusive DATETIME2 = DATEADD(DAY, 1, CONVERT(DATETIME2, CONVERT(DATE, @EndDate)));

    IF @StartCutoff >= @EndExclusive
        THROW 52130, N'The inventory trend start date must be on or before the end date.', 1;

    ;WITH InventorySnapshots AS
    (
        SELECT
            i.VariantId,
            v.CreatedAt,
            p.IsActive AS ProductIsActive,
            v.IsActive AS VariantIsActive,
            CASE WHEN v.CreatedAt >= @StartCutoff THEN 0
                 ELSE i.CurrentStock - ISNULL(SUM(CASE WHEN l.CreatedAt >= @StartCutoff THEN l.QuantityChanged ELSE 0 END), 0)
            END AS StartStock,
            CASE WHEN v.CreatedAt >= @EndExclusive THEN 0
                 ELSE i.CurrentStock - ISNULL(SUM(CASE WHEN l.CreatedAt >= @EndExclusive THEN l.QuantityChanged ELSE 0 END), 0)
            END AS EndStock
        FROM dbo.v_VisibleInventories i
        JOIN dbo.v_VisibleProductVariants v ON v.Id = i.VariantId
        JOIN dbo.v_VisibleProductColors c ON c.Id = v.ProductColorId
        JOIN dbo.v_VisibleProducts p ON p.Id = c.ProductId
        LEFT JOIN dbo.v_VisibleStockAuditLogs l ON l.VariantId = i.VariantId
        GROUP BY i.VariantId, i.CurrentStock, v.CreatedAt, p.IsActive, v.IsActive
    )
    SELECT
        CONVERT(INT, ISNULL(SUM(StartStock), 0)) AS StartTotalUnits,
        CONVERT(INT, ISNULL(SUM(EndStock), 0)) AS EndTotalUnits,
        CONVERT(INT, ISNULL(SUM(CASE WHEN CreatedAt < @StartCutoff AND ProductIsActive = 1 AND VariantIsActive = 1 THEN 1 ELSE 0 END), 0)) AS StartActiveSkus,
        CONVERT(INT, ISNULL(SUM(CASE WHEN CreatedAt < @EndExclusive AND ProductIsActive = 1 AND VariantIsActive = 1 THEN 1 ELSE 0 END), 0)) AS EndActiveSkus
    FROM InventorySnapshots;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminInventoryReport
AS
BEGIN
    SET NOCOUNT ON;
    SELECT b.Name AS Brand, COUNT(*) AS VariantCount, SUM(i.CurrentStock) AS OnHandStock,
           SUM(i.CurrentStock - i.ReservedStock) AS AvailableStock,
           SUM(CASE WHEN i.IsLowStock = 1 THEN 1 ELSE 0 END) AS LowStockCount
    FROM dbo.v_VisibleInventories i JOIN dbo.v_VisibleProductVariants v ON v.Id = i.VariantId
    JOIN dbo.v_VisibleProductColors c ON c.Id = v.ProductColorId
    JOIN dbo.v_VisibleProducts p ON p.Id = c.ProductId JOIN dbo.Brands b ON b.Id = p.BrandId
    GROUP BY b.Name ORDER BY b.Name;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminBrandInventoryDetails
AS
BEGIN
    SET NOCOUNT ON;
    SELECT b.Name AS Brand, p.Id AS ProductId, v.Id AS VariantId,
           p.Name AS ProductName, cat.Name AS CategoryName, p.MainImageUrl,
           c.Color, v.Size, v.SKU, i.CurrentStock AS OnHandStock,
           i.CurrentStock - i.ReservedStock AS AvailableStock,
           i.ReorderPoint,
           CASE WHEN i.CurrentStock - i.ReservedStock <= 0 THEN N'out_of_stock'
                WHEN i.CurrentStock - i.ReservedStock <= i.ReorderPoint THEN N'low_stock'
                ELSE N'in_stock' END AS StockStatus
    FROM dbo.v_VisibleInventories i
    JOIN dbo.v_VisibleProductVariants v ON v.Id = i.VariantId
    JOIN dbo.v_VisibleProductColors c ON c.Id = v.ProductColorId
    JOIN dbo.v_VisibleProducts p ON p.Id = c.ProductId
    JOIN dbo.Brands b ON b.Id = p.BrandId
    JOIN dbo.Categories cat ON cat.Id = p.CategoryId
    ORDER BY b.Name, p.Name, c.Color, v.Size;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminInventoryProducts
    @Search NVARCHAR(200) = NULL,
    @Brand NVARCHAR(100) = NULL,
    @Category NVARCHAR(100) = NULL,
    @StockStatus NVARCHAR(50) = 'all'
AS
BEGIN
    SET NOCOUNT ON;
    SET @Search = NULLIF(LTRIM(RTRIM(@Search)), N'');
    SET @Brand = NULLIF(LTRIM(RTRIM(@Brand)), N'');
    SET @Category = NULLIF(LTRIM(RTRIM(@Category)), N'');
    IF @Brand = 'all' SET @Brand = NULL;
    IF @Category = 'all' SET @Category = NULL;
    IF @StockStatus IS NULL OR LTRIM(RTRIM(@StockStatus)) = '' SET @StockStatus = 'all';

    SELECT 
        p.Id AS ProductId,
        p.Name AS ProductName,
        p.Slug,
        b.Id AS BrandId,
        b.Name AS BrandName,
        c.Id AS CategoryId,
        c.Name AS CategoryName,
        p.RidingStyle,
        p.BasePrice,
        p.DiscountPercentage,
        CAST(p.BasePrice * (1.0 - (p.DiscountPercentage / 100.0)) AS DECIMAL(18,2)) AS EffectivePrice,
        p.MainImageUrl,
        p.IsActive,
        ISNULL(SUM(i.CurrentStock), 0) AS TotalStock,
        ISNULL(SUM(i.ReservedStock), 0) AS ReservedStock,
        ISNULL(SUM(i.CurrentStock), 0) - ISNULL(SUM(i.ReservedStock), 0) AS AvailableStock,
        COUNT(DISTINCT pv.Id) AS VariantCount,
        ISNULL(MIN(pv.SKU), N'HC-DEFAULT') AS SampleSKU,
        CASE 
            WHEN ISNULL(SUM(i.CurrentStock), 0) <= 0 THEN 'out_of_stock'
            WHEN ISNULL(SUM(i.CurrentStock), 0) <= 15 THEN 'low_stock'
            ELSE 'in_stock'
        END AS StockStatus
    FROM dbo.v_VisibleProducts p
    INNER JOIN dbo.Brands b ON p.BrandId = b.Id
    INNER JOIN dbo.Categories c ON p.CategoryId = c.Id
    LEFT JOIN dbo.v_VisibleProductColors pc ON pc.ProductId = p.Id
    LEFT JOIN dbo.v_VisibleProductVariants pv ON pv.ProductColorId = pc.Id AND pv.IsActive = 1
    LEFT JOIN dbo.v_VisibleInventories i ON i.VariantId = pv.Id
    WHERE (@Search IS NULL OR p.Name LIKE N'%' + @Search + N'%' OR b.Name LIKE N'%' + @Search + N'%' OR pv.SKU LIKE N'%' + @Search + N'%')
      AND (@Brand IS NULL OR b.Name = @Brand)
      AND (@Category IS NULL OR c.Name = @Category OR c.Slug = @Category)
    GROUP BY p.Id, p.Name, p.Slug, b.Id, b.Name, c.Id, c.Name, p.RidingStyle, p.BasePrice, p.DiscountPercentage, p.MainImageUrl, p.IsActive
    HAVING (@StockStatus = 'all')
        OR (@StockStatus = 'in_stock' AND ISNULL(SUM(i.CurrentStock), 0) > 15)
        OR (@StockStatus = 'low_stock' AND ISNULL(SUM(i.CurrentStock), 0) > 0 AND ISNULL(SUM(i.CurrentStock), 0) <= 15)
        OR (@StockStatus = 'out_of_stock' AND ISNULL(SUM(i.CurrentStock), 0) <= 0)
    ORDER BY p.Id ASC;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminInventoryVariants
    @Search NVARCHAR(200) = NULL,
    @Brand NVARCHAR(100) = NULL,
    @Category NVARCHAR(100) = NULL,
    @StockStatus NVARCHAR(50) = N'all',
    @ProductId INT = NULL,
    @VariantId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET @Search = NULLIF(LTRIM(RTRIM(@Search)), N'');
    SET @Brand = NULLIF(LTRIM(RTRIM(@Brand)), N'');
    SET @Category = NULLIF(LTRIM(RTRIM(@Category)), N'');
    IF @Brand = N'all' SET @Brand = NULL;
    IF @Category = N'all' SET @Category = NULL;
    IF @StockStatus IS NULL OR LTRIM(RTRIM(@StockStatus)) = N'' SET @StockStatus = N'all';

    SELECT v.Id AS VariantId, p.Id AS ProductId, b.Name AS BrandName,
           p.Name AS ProductName, cat.Name AS CategoryName, c.Color, c.ColorHex,
           v.Size, ISNULL(i.CurrentStock, 0) AS CurrentStock,
           ISNULL(i.ReservedStock, 0) AS ReservedStock,
           ISNULL(i.CurrentStock, 0) - ISNULL(i.ReservedStock, 0) AS AvailableStock,
           ISNULL(i.ReorderPoint, 3) AS ReorderPoint,
           dbo.fn_CalculateEffectivePrice(p.BasePrice, v.PriceAdjustment,
               p.DiscountPercentage, p.DiscountType, p.DiscountAmount,
               p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive) AS EffectivePrice,
           v.SKU, p.MainImageUrl,
           CASE WHEN ISNULL(i.CurrentStock, 0) - ISNULL(i.ReservedStock, 0) <= 0 THEN N'out_of_stock'
                WHEN ISNULL(i.CurrentStock, 0) - ISNULL(i.ReservedStock, 0) <= ISNULL(i.ReorderPoint, 3) THEN N'low_stock'
                ELSE N'in_stock' END AS StockStatus
    FROM dbo.v_VisibleProductVariants v
    JOIN dbo.v_VisibleProductColors c ON c.Id = v.ProductColorId
    JOIN dbo.v_VisibleProducts p ON p.Id = c.ProductId
    JOIN dbo.Brands b ON b.Id = p.BrandId
    JOIN dbo.Categories cat ON cat.Id = p.CategoryId
    LEFT JOIN dbo.v_VisibleInventories i ON i.VariantId = v.Id
    WHERE v.IsActive = 1 AND p.IsActive = 1
      AND (@ProductId IS NULL OR p.Id = @ProductId)
      AND (@VariantId IS NULL OR v.Id = @VariantId)
      AND (@Search IS NULL OR p.Name LIKE N'%' + @Search + N'%'
           OR b.Name LIKE N'%' + @Search + N'%' OR cat.Name LIKE N'%' + @Search + N'%'
           OR v.SKU LIKE N'%' + @Search + N'%' OR c.Color LIKE N'%' + @Search + N'%'
           OR CONCAT(b.Name, N' ', p.Name) LIKE N'%' + @Search + N'%'
           OR CONCAT(b.Name, N' ', p.Name, N' ', c.Color) LIKE N'%' + @Search + N'%'
           OR CONCAT(b.Name, N' ', p.Name, N' ', c.Color, N' ', v.Size) LIKE N'%' + @Search + N'%'
           OR CONCAT(p.Name, N' ', c.Color) LIKE N'%' + @Search + N'%')
      AND (@Brand IS NULL OR b.Name = @Brand)
      AND (@Category IS NULL OR cat.Name = @Category OR cat.Slug = @Category)
      AND (@StockStatus = N'all'
           OR (@StockStatus = N'in_stock' AND ISNULL(i.CurrentStock, 0) - ISNULL(i.ReservedStock, 0) > ISNULL(i.ReorderPoint, 3))
           OR (@StockStatus = N'low_stock' AND ISNULL(i.CurrentStock, 0) - ISNULL(i.ReservedStock, 0) BETWEEN 1 AND ISNULL(i.ReorderPoint, 3))
           OR (@StockStatus = N'out_of_stock' AND ISNULL(i.CurrentStock, 0) - ISNULL(i.ReservedStock, 0) <= 0))
    ORDER BY b.Name, p.Name, c.Color, v.Size;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminSellableVariants
    @Search NVARCHAR(200) = NULL,
    @Brand NVARCHAR(100) = NULL,
    @Category NVARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET @Search = NULLIF(LTRIM(RTRIM(@Search)), N'');
    SET @Brand = NULLIF(LTRIM(RTRIM(@Brand)), N'');
    SET @Category = NULLIF(LTRIM(RTRIM(@Category)), N'');
    SELECT v.Id AS VariantId, p.Id AS ProductId, v.SKU,
           p.Name AS ProductName, b.Name AS Brand, cat.Name AS Category,
           p.MainImageUrl, c.Color, c.ColorHex, v.Size,
           i.CurrentStock - i.ReservedStock AS AvailableStock,
           dbo.fn_CalculateEffectivePrice(p.BasePrice, v.PriceAdjustment,
               p.DiscountPercentage, p.DiscountType, p.DiscountAmount,
               p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive) AS UnitPrice,
           CASE WHEN i.CurrentStock - i.ReservedStock <= 0 THEN N'out_of_stock'
                WHEN i.CurrentStock - i.ReservedStock <= i.ReorderPoint THEN N'low_stock'
                ELSE N'in_stock' END AS StockStatus
    FROM dbo.v_VisibleProductVariants v
    JOIN dbo.v_VisibleProductColors c ON c.Id = v.ProductColorId
    JOIN dbo.v_VisibleProducts p ON p.Id = c.ProductId
    JOIN dbo.Brands b ON b.Id = p.BrandId
    JOIN dbo.Categories cat ON cat.Id = p.CategoryId
    JOIN dbo.v_VisibleInventories i ON i.VariantId = v.Id
    WHERE p.IsActive = 1 AND v.IsActive = 1
      AND (@Search IS NULL OR p.Name LIKE N'%' + @Search + N'%'
           OR b.Name LIKE N'%' + @Search + N'%'
           OR v.SKU LIKE N'%' + @Search + N'%'
           OR c.Color LIKE N'%' + @Search + N'%'
           OR CONCAT(b.Name, N' ', p.Name) LIKE N'%' + @Search + N'%')
      AND (@Brand IS NULL OR b.Name = @Brand)
      AND (@Category IS NULL OR cat.Name = @Category)
    ORDER BY b.Name, p.Name, c.Color, v.Size;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminCatalogProducts 
    @Search NVARCHAR(200) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET @Search = NULLIF(LTRIM(RTRIM(@Search)), N'');

    SELECT 
        p.Id, 
        p.Name, 
        p.Slug, 
        p.Description, 
        p.CategoryId, 
        c.Name AS Category,
        p.BrandId, 
        b.Name AS Brand, 
        p.RidingStyle, 
        p.BasePrice, 
        p.DiscountPercentage,
        p.DiscountType,
        p.DiscountAmount,
        p.DiscountStartDate,
        p.DiscountEndDate,
        p.DiscountIsActive,
        dbo.fn_CalculateEffectivePrice(p.BasePrice, 0, p.DiscountPercentage, p.DiscountType, p.DiscountAmount, p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive) AS EffectivePrice,
        p.MainImageUrl, 
        p.IsFeatured, 
        p.IsActive, 
        p.CreatedAt,
        (SELECT COUNT(*) FROM dbo.v_VisibleProductVariants v JOIN dbo.v_VisibleProductColors pc ON pc.Id = v.ProductColorId WHERE pc.ProductId = p.Id) AS VariantCount
    FROM dbo.v_VisibleProducts p 
    JOIN dbo.Categories c ON c.Id = p.CategoryId 
    JOIN dbo.Brands b ON b.Id = p.BrandId
    WHERE @Search IS NULL 
       OR p.Name LIKE N'%' + @Search + N'%' 
       OR p.Slug LIKE N'%' + @Search + N'%'
       OR b.Name LIKE N'%' + @Search + N'%'
       OR c.Name LIKE N'%' + @Search + N'%'
       OR EXISTS (
           SELECT 1 
           FROM dbo.v_VisibleProductVariants v 
           JOIN dbo.v_VisibleProductColors pc ON pc.Id = v.ProductColorId 
           WHERE pc.ProductId = p.Id AND v.SKU LIKE N'%' + @Search + N'%'
       )
    ORDER BY p.CreatedAt DESC, p.Id DESC;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminGlobalSearch
    @Query NVARCHAR(100),
    @Limit INT = 8
AS
BEGIN
    SET NOCOUNT ON;
    SET @Query = LTRIM(RTRIM(@Query));
    IF @Query IS NULL OR LEN(@Query) < 1
    BEGIN
        SELECT TOP 0 '' AS Category, '' AS Title, '' AS Subtitle, '' AS Url, '' AS Badge;
        RETURN;
    END;

    -- 1. Point of Sale (Direct POS Action for sellable in-stock items)
    SELECT TOP (@Limit)
        'Point of Sale' AS Category,
        CONCAT(b.Name, ' ', p.Name, ' (', c.Color, ' - ', v.Size, ')') AS Title,
        CONCAT(NCHAR(8369), FORMAT(dbo.fn_CalculateEffectivePrice(p.BasePrice, v.PriceAdjustment, p.DiscountPercentage, p.DiscountType, p.DiscountAmount, p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive), 'N2'), NCHAR(32), NCHAR(8226), NCHAR(32), ISNULL(i.CurrentStock, 0), ' in stock', NCHAR(32), NCHAR(8226), NCHAR(32), 'SKU: ', v.SKU) AS Subtitle,
        CONCAT('/Admin/POS.aspx?search=', v.SKU) AS Url,
        'Sell in POS' AS Badge
    FROM dbo.v_VisibleProductVariants v
    JOIN dbo.v_VisibleProductColors c ON c.Id = v.ProductColorId
    JOIN dbo.v_VisibleProducts p ON p.Id = c.ProductId
    JOIN dbo.Brands b ON b.Id = p.BrandId
    LEFT JOIN dbo.v_VisibleInventories i ON i.VariantId = v.Id
    WHERE v.IsActive = 1 AND p.IsActive = 1 AND ISNULL(i.CurrentStock, 0) > 0
      AND (
          p.Name LIKE '%' + @Query + '%'
          OR b.Name LIKE '%' + @Query + '%'
          OR CONCAT(b.Name, ' ', p.Name) LIKE '%' + @Query + '%'
          OR CONCAT(b.Name, ' ', p.Name, ' ', c.Color) LIKE '%' + @Query + '%'
          OR v.SKU LIKE '%' + @Query + '%'
          OR c.Color LIKE '%' + @Query + '%'
      )

    UNION ALL

    -- 2. Brands Matching Query
    SELECT TOP (@Limit)
        'Brands' AS Category,
        b.Name AS Title,
        CONCAT((SELECT COUNT(*) FROM dbo.v_VisibleProducts p WHERE p.BrandId = b.Id), ' Helmet Models in Catalog') AS Subtitle,
        CONCAT('/Admin/Inventory.aspx?brand=', b.Name) AS Url,
        'Brand' AS Badge
    FROM dbo.Brands b
    WHERE b.Name LIKE '%' + @Query + '%'

    UNION ALL

    -- 3. Catalog Models
    SELECT TOP (@Limit)
        'Catalog' AS Category,
        CONCAT(b.Name, ' ', p.Name) AS Title,
        CONCAT(cat.Name, NCHAR(32), NCHAR(8226), NCHAR(32), p.RidingStyle, NCHAR(32), NCHAR(8226), NCHAR(32), 'Base: ', NCHAR(8369), FORMAT(p.BasePrice, 'N2')) AS Subtitle,
        CONCAT('/Admin/Catalog.aspx?id=', p.Id) AS Url,
        b.Name AS Badge
    FROM dbo.v_VisibleProducts p
    JOIN dbo.Brands b ON b.Id = p.BrandId
    JOIN dbo.Categories cat ON cat.Id = p.CategoryId
    WHERE p.Name LIKE '%' + @Query + '%'
       OR b.Name LIKE '%' + @Query + '%'
       OR CONCAT(b.Name, ' ', p.Name) LIKE '%' + @Query + '%'

    UNION ALL

    -- 4. Inventory Variants (Color, Size, SKU)
    SELECT TOP (@Limit)
        'Inventory' AS Category,
        CONCAT(b.Name, ' ', p.Name, ' (', c.Color, ' - ', v.Size, ')') AS Title,
        CONCAT('Stock: ', ISNULL(i.CurrentStock,0), ' units', NCHAR(32), NCHAR(8226), NCHAR(32), 'SKU: ', v.SKU) AS Subtitle,
        CONCAT('/Admin/Inventory.aspx?q=', v.SKU) AS Url,
        CASE WHEN ISNULL(i.CurrentStock,0) <= 0 THEN 'Out of Stock' 
             WHEN ISNULL(i.CurrentStock,0) <= ISNULL(i.ReorderPoint,3) THEN 'Low Stock' 
             ELSE 'In Stock' END AS Badge
    FROM dbo.v_VisibleProductVariants v
    JOIN dbo.v_VisibleProductColors c ON c.Id = v.ProductColorId
    JOIN dbo.v_VisibleProducts p ON p.Id = c.ProductId
    JOIN dbo.Brands b ON b.Id = p.BrandId
    LEFT JOIN dbo.v_VisibleInventories i ON i.VariantId = v.Id
    WHERE p.Name LIKE '%' + @Query + '%'
       OR b.Name LIKE '%' + @Query + '%'
       OR CONCAT(b.Name, ' ', p.Name) LIKE '%' + @Query + '%'
       OR CONCAT(b.Name, ' ', p.Name, ' ', c.Color) LIKE '%' + @Query + '%'
       OR v.SKU LIKE '%' + @Query + '%'
       OR c.Color LIKE '%' + @Query + '%'

    UNION ALL

    -- 5. Orders
    SELECT TOP (@Limit)
        'Orders' AS Category,
        CONCAT(o.OrderNumber, ' — ', o.CustomerName) AS Title,
        CONCAT(NCHAR(8369), FORMAT(o.TotalAmount, 'N2'), NCHAR(32), NCHAR(8226), NCHAR(32), o.Status, NCHAR(32), NCHAR(8226), NCHAR(32), o.OrderSource) AS Subtitle,
        CONCAT('/Admin/Orders.aspx?q=', o.OrderNumber) AS Url,
        o.Status AS Badge
    FROM dbo.Orders o
    WHERE o.OrderNumber LIKE '%' + @Query + '%'
       OR o.CustomerName LIKE '%' + @Query + '%'
       OR o.CustomerEmail LIKE '%' + @Query + '%'
       OR o.CustomerPhone LIKE '%' + @Query + '%'

    UNION ALL

    -- 6. Users
    SELECT TOP (@Limit)
        'Users' AS Category,
        CONCAT(u.FirstName, N' ', u.LastName) AS Title,
        CONCAT(u.Email, NCHAR(32), NCHAR(8226), NCHAR(32), ISNULL(u.PhoneNumber, 'No phone')) AS Subtitle,
        CONCAT('/Admin/Users.aspx?q=', u.Email) AS Url,
        r.Name AS Badge
    FROM dbo.Users u
    JOIN dbo.Roles r ON r.Id = u.RoleId
    WHERE CONCAT(u.FirstName, N' ', u.LastName) LIKE '%' + @Query + '%'
       OR u.Email LIKE '%' + @Query + '%'
       OR u.PhoneNumber LIKE '%' + @Query + '%';
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminStockAuditLogs
    @VariantId INT = NULL,
    @Search NVARCHAR(200) = NULL,
    @Limit INT = 100
AS
BEGIN
    SET NOCOUNT ON;
    SET @Search = NULLIF(LTRIM(RTRIM(@Search)), N'');

    SELECT TOP (@Limit)
        l.Id,
        l.VariantId,
        b.Name AS BrandName,
        p.Id AS ProductId,
        p.Name AS ProductName,
        c.Color,
        v.Size,
        v.SKU,
        l.ChangeType,
        l.PreviousStock,
        l.QuantityChanged,
        l.NewStock,
        l.ReferenceNumber,
        l.Notes,
        l.CreatedAt,
        ISNULL(NULLIF(LTRIM(RTRIM(CONCAT(u.FirstName, N' ', u.LastName))), N''), N'Staff Admin') AS PerformedBy
    FROM dbo.v_VisibleStockAuditLogs l
    JOIN dbo.v_VisibleProductVariants v ON v.Id = l.VariantId
    JOIN dbo.v_VisibleProductColors c ON c.Id = v.ProductColorId
    JOIN dbo.v_VisibleProducts p ON p.Id = c.ProductId
    JOIN dbo.Brands b ON b.Id = p.BrandId
    LEFT JOIN dbo.Users u ON u.Id = l.UserId
    WHERE (@VariantId IS NULL OR l.VariantId = @VariantId)
      AND (
          @Search IS NULL
          OR b.Name LIKE N'%' + @Search + N'%'
          OR p.Name LIKE N'%' + @Search + N'%'
          OR v.SKU LIKE N'%' + @Search + N'%'
          OR c.Color LIKE N'%' + @Search + N'%'
          OR l.ReferenceNumber LIKE N'%' + @Search + N'%'
      )
    ORDER BY l.CreatedAt DESC, l.Id DESC;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminStockHistory @VariantId INT, @Limit INT = 50
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP (@Limit) l.Id, l.VariantId, l.ChangeType, l.PreviousStock, l.QuantityChanged,
           l.NewStock, l.ReferenceNumber, l.Notes, l.CreatedAt,
           CONCAT(u.FirstName, N' ', u.LastName) AS PerformedBy
    FROM dbo.v_VisibleStockAuditLogs l LEFT JOIN dbo.Users u ON u.Id = l.UserId
    WHERE l.VariantId = @VariantId ORDER BY l.CreatedAt DESC, l.Id DESC;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminRecentActivity @Limit INT = 8
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP (@Limit) ActivityType, Reference, Detail, Actor, CreatedAt
    FROM (
        SELECT N'Order' AS ActivityType, o.OrderNumber AS Reference,
               o.Status AS Detail, o.CustomerName AS Actor,
               COALESCE(o.UpdatedAt, o.CreatedAt) AS CreatedAt
        FROM dbo.Orders o
        UNION ALL
        SELECT N'Stock', COALESCE(l.ReferenceNumber, v.SKU),
               CONCAT(v.SKU, N' - ', l.ChangeType, N' ',
                   CASE WHEN l.QuantityChanged > 0 THEN N'+' ELSE N'' END, l.QuantityChanged),
               COALESCE(NULLIF(CONCAT(u.FirstName, N' ', u.LastName), N' '), N'System'), l.CreatedAt
        FROM dbo.v_VisibleStockAuditLogs l
        JOIN dbo.v_VisibleProductVariants v ON v.Id = l.VariantId
        LEFT JOIN dbo.Users u ON u.Id = l.UserId
    ) activity
    ORDER BY CreatedAt DESC;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminVariants @ProductId INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT v.Id, v.ProductColorId, c.Color, v.SKU, v.Size, v.PriceAdjustment, v.IsActive,
           ISNULL(i.CurrentStock, 0) AS CurrentStock, ISNULL(i.ReservedStock, 0) AS ReservedStock,
           ISNULL(i.ReorderPoint, 3) AS ReorderPoint
    FROM dbo.v_VisibleProductVariants v JOIN dbo.v_VisibleProductColors c ON c.Id = v.ProductColorId
    LEFT JOIN dbo.v_VisibleInventories i ON i.VariantId = v.Id
    WHERE c.ProductId = @ProductId ORDER BY c.Color, v.Size;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminColors @ProductId INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT c.Id, c.ProductId, c.Color, c.ColorHex, c.ColorType, c.GradientAngle,
           (SELECT ColorHex FROM dbo.ProductColorStops WHERE ProductColorId = c.Id AND StopOrder = 1) AS Stop1,
           (SELECT ColorHex FROM dbo.ProductColorStops WHERE ProductColorId = c.Id AND StopOrder = 2) AS Stop2,
           (SELECT ColorHex FROM dbo.ProductColorStops WHERE ProductColorId = c.Id AND StopOrder = 3) AS Stop3,
           (SELECT ColorHex FROM dbo.ProductColorStops WHERE ProductColorId = c.Id AND StopOrder = 4) AS Stop4
    FROM dbo.v_VisibleProductColors c WHERE c.ProductId = @ProductId ORDER BY c.Color;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminGetProductComplete
    @ProductId INT
AS
BEGIN
    SET NOCOUNT ON;

    -- Result 1: Product Header Info
    SELECT p.Id, p.CategoryId, p.BrandId, p.Name, p.Slug, p.Description, p.RidingStyle,
           p.BasePrice, p.DiscountPercentage, p.DiscountType, p.DiscountAmount,
           p.DiscountStartDate, p.DiscountEndDate, p.DiscountIsActive,
           p.MainImageUrl, p.IsFeatured, p.IsActive,
           b.Name AS BrandName, c.Name AS CategoryName
    FROM dbo.v_VisibleProducts p
    INNER JOIN dbo.Brands b ON b.Id = p.BrandId
    INNER JOIN dbo.Categories c ON c.Id = p.CategoryId
    WHERE p.Id = @ProductId;

    -- Result 2: Product Specifications
    SELECT d.SpecificationKey, d.DisplayName, v.SpecificationValue,
           ISNULL(cs.DisplayOrder, 99) AS DisplayOrder
    FROM dbo.ProductSpecificationValues v
    INNER JOIN dbo.SpecificationDefinitions d ON d.Id = v.SpecificationId
    LEFT JOIN dbo.CategorySpecifications cs ON cs.SpecificationId = d.Id AND cs.CategoryId = (SELECT CategoryId FROM dbo.v_VisibleProducts WHERE Id = @ProductId)
    WHERE v.ProductId = @ProductId
    ORDER BY DisplayOrder, d.DisplayName;

    -- Result 3: Product Colors & Color Stops
    SELECT pc.Id, pc.Color, pc.ColorHex, pc.ColorType, pc.GradientAngle
    FROM dbo.v_VisibleProductColors pc
    WHERE pc.ProductId = @ProductId
    ORDER BY pc.Id;

    -- Result 4: Product Variants & Stocks
    SELECT pv.Id AS VariantId, pv.ProductColorId, pc.Color, pc.ColorHex, pv.Size, pv.SKU,
           pv.PriceAdjustment, pv.IsActive,
           ISNULL(inv.CurrentStock, 0) AS CurrentStock,
           ISNULL(inv.ReorderPoint, 3) AS ReorderPoint
    FROM dbo.v_VisibleProductVariants pv
    INNER JOIN dbo.v_VisibleProductColors pc ON pc.Id = pv.ProductColorId
    LEFT JOIN dbo.v_VisibleInventories inv ON inv.VariantId = pv.Id
    WHERE pc.ProductId = @ProductId
    ORDER BY pc.Id, pv.Size;

    -- Result 5: Product Gallery Images
    SELECT Id, ImageUrl, AltText, DisplayOrder
    FROM dbo.ProductGalleryImages
    WHERE ProductId = @ProductId
    ORDER BY DisplayOrder;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_AdminReviews @Limit INT = 100
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP (@Limit) r.Id, p.Name AS ProductName, r.ProductId, r.ReviewerName, r.Rating,
           r.Title, r.Comment, r.IsVerifiedPurchase, r.IsHidden, r.CreatedAt,
           (SELECT COUNT(*) FROM dbo.ReviewReports rr WHERE rr.ReviewId = r.Id) AS ReportCount
    FROM dbo.ProductReviews r JOIN dbo.v_VisibleProducts p ON p.Id = r.ProductId
    ORDER BY (SELECT COUNT(*) FROM dbo.ReviewReports rr WHERE rr.ReviewId = r.Id) DESC, r.CreatedAt DESC;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_GetProductReviews
    @ProductId INT,
    @IncludeHidden BIT = 0
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        Id,
        ProductId,
        UserId,
        OrderId,
        ReviewerName,
        Rating,
        Title,
        Comment,
        IsVerifiedPurchase,
        (SELECT COUNT(*) FROM dbo.ReviewReports reports WHERE reports.ReviewId = reviews.Id) AS FlagCount,
        IsHidden,
        CreatedAt
    FROM dbo.ProductReviews reviews
    WHERE ProductId = @ProductId AND EXISTS (SELECT 1 FROM dbo.v_VisibleProducts p WHERE p.Id = @ProductId)
      AND (@IncludeHidden = 1 OR IsHidden = 0)
    ORDER BY CreatedAt DESC;
END;
GO
CREATE OR ALTER PROCEDURE dbo.sp_GetProductSpecifications
    @ProductId INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT d.SpecificationKey,
           d.DisplayName,
           v.SpecificationValue,
           cs.DisplayOrder
    FROM dbo.v_VisibleProducts p
    INNER JOIN dbo.CategorySpecifications cs ON cs.CategoryId = p.CategoryId
    INNER JOIN dbo.SpecificationDefinitions d ON d.Id = cs.SpecificationId AND d.IsActive = 1
    INNER JOIN dbo.ProductSpecificationValues v ON v.ProductId = p.Id AND v.SpecificationId = d.Id
    WHERE p.Id = @ProductId AND p.IsActive = 1
    ORDER BY cs.DisplayOrder, d.DisplayName;
END;
GO
